name = "DifferenceBase"
uuid = "0b0e09cb-e13c-4ad2-9b92-e9d81af820a1"
authors = ["Lars Schütz"]

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
