name = "DifferencesBase"
uuid = "f7c07657-0d0a-4d46-b086-01df223a7b4f"
authors = ["Lars Schütz"]
version = "0.15.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.5"
