name = "DifferencesBase"
uuid = "f7c07657-0d0a-4d46-b086-01df223a7b4f"
authors = ["Lars Schütz"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.2"
OrderedCollections = "1.2.0"
